### PR TITLE
feature(hook): CloudTrail Log Validation

### PR DESCRIPTION
**Pull request by jonloza**
*Issue #, if available:*

*Description of changes:*
Added cfn hook rule for check cloudtrail log file validation

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by ericzbeard — COMMENTED** [review]
We need a `test/setup.yml` to create the prerequisites needed for contract testing to succeed.

**Comment by jonloza** [comment]
> 

@ericzbeard 
Updated with setup.yaml. I think I did it right ?
please let me know !

thank you

**Comment by ericzbeard** [comment]
> > 
> 
> @ericzbeard Updated with setup.yaml. I think I did it right ? please let me know !
> 
> thank you

I don't see it

**Comment by jonloza** [comment]
@ericzbeard my fault missed it.. updated now thank you

**Pull request merged**
